name: Almalinux Build
permissions:
  contents: read
  pull-requests: write

  # Triggers the workflow on all pushes to main, all pull and merge requests
on:
  pull_request:
  merge_group:
  push:
    branches: [ main ]
    tags: [ '*' ]
    paths-ignore:
      - "**/*.md"
      - "release_notes/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-on-almalinux:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    # Skip this entire job if the commit was made by the merge queue bot
    if: github.event.head_commit.committer.name != 'github-merge-queue[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Fix Ownership
        run: |
          # recent versions of Git refuse to touch a repository whose on-disk owner 
          # doesn’t match the UID that is running the command
          # mark the workspace (and any nested path) as safe
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"/src
      - name: Build gemc
        run: |
          ./ci/build_gemc.sh
          echo "github.event.head_commit.committer.name: ${{ github.event.head_commit.committer.name }}"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gemc
          path: |
            /cvmfs/oasis.opensciencegrid.org/jlab/geant4/bin
            /cvmfs/oasis.opensciencegrid.org/jlab/geant4/api
            /cvmfs/oasis.opensciencegrid.org/jlab/geant4/clas12.sqlite
            /cvmfs/oasis.opensciencegrid.org/jlab/geant4/experiments

